### ISSUE TITLE
Error al momento de darle require 

### ISSUE THREAD

**Issue by lfacchinelli** [emaraschio/ricky_ipsum#1]
irb(main):001:0> require 'ricky_ipsum'
SyntaxError: /var/lib/gems/1.9.1/gems/ricky_ipsum-1.0.0/lib/ricky_ipsum.rb:7: invalid multibyte char (US-ASCII)
/var/lib/gems/1.9.1/gems/ricky_ipsum-1.0.0/lib/ricky_ipsum.rb:7: invalid multibyte char (US-ASCII)
/var/lib/gems/1.9.1/gems/ricky_ipsum-1.0.0/lib/ricky_ipsum.rb:7: syntax error, unexpected $end, expecting ']'
      "VOY A REÍR... VOY A GOZAR... VIVIR MI ...
                 ^
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in`rescue in require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
    from (irb):1
    from /usr/bin/irb:12:in`<main>'
irb(main):002:0> require "ricky_ipsum"
SyntaxError: /var/lib/gems/1.9.1/gems/ricky_ipsum-1.0.0/lib/ricky_ipsum.rb:7: invalid multibyte char (US-ASCII)
/var/lib/gems/1.9.1/gems/ricky_ipsum-1.0.0/lib/ricky_ipsum.rb:7: invalid multibyte char (US-ASCII)
/var/lib/gems/1.9.1/gems/ricky_ipsum-1.0.0/lib/ricky_ipsum.rb:7: syntax error, unexpected $end, expecting ']'
      "VOY A REÍR... VOY A GOZAR... VIVIR MI ...
                 ^
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from (irb):2
    from /usr/bin/irb:12:in `<main>'

**Comment by emaraschio** [comment]
This can help -> http://stackoverflow.com/questions/19910181/ruby-error-invalid-multibyte-char-us-ascii/19910494#19910494

it's related to encoding not a compile error, please update your ruby version or just do the workaround that the post suggest!
